# Generated by Django 2.2 on 2021-01-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
    ]
