# Generated by Django 2.2 on 2021-01-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis_senhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField()),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_sistema', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscar_categorias', to='perfis_senhas.Categoria_senha')),
            ],
        ),
        migrations.CreateModel(
            name='Status_senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_status', models.IntegerField()),
                ('nome_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('nome_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.AddField(
            model_name='senha',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscar_status', to='perfis_senhas.Status_senha'),
        ),
        migrations.AddField(
            model_name='senha',
            name='Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscar_tipos', to='perfis_senhas.Tipo_senha'),
        ),
    ]
