# Generated by Django 2.2 on 2021-01-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis_senhas', '0002_auto_20210131_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senha',
            old_name='senha_sistema',
            new_name='senha',
        ),
    ]
